version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./build/db/:/var/lib/postgresql/data
  backend:
    image: backend-app
    volumes:
      - ./configs/backend.config.yaml:/etc/app/application.yaml
    ports:
      - 8080:8080