version: '3.8'
services:
  db:
    image: postgres:12.10
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./build/db/:/var/lib/postgresql/data
  backend:
    image: backend-app
    build:
      context: backend-app
      target: prod
    volumes:
      - ./configs/backend.config.yaml:/etc/app/application.yaml
    ports:
      - "8080:8080"
  frontend:
    image: frontend-app
    ports:
      - "80:80"
    volumes:
      - ./configs/frontend.config.js:/usr/share/nginx/html/config.js
    build:
      context: frontend-app
      target: prod