spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
